# -*- coding: utf-8 -*-
"""text_reuse.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vA5IUP6L2iN_6BkK0zm3OOoJXi1EslL0
"""

# def get_last_names():
#   lowercase_last_names = []
#   for author in cited_authors:     # you'll need to .split() each author and take only the last word — we get first names as well as last but you only want to check the last
#     lowercase_last_names.append(author.lower())
#   return lowercase_last_names

def theres_an_author_match(citing_set, lowercase_last_names):
  flatten_set_of_tuples()    # you need to put citing_set in the parens like all_words_in_chunk = flatten_set_of_tuples(citing_set)
  author_match = False          # you could set this initially to False, and set it to True if match is found
  #check if author name matches any tokens in any of 3 grams
  for item in list:      # ah — you can simplify the nested loops by just saying if name in all_words_in_chunk: where you currently say if item == name:
    for name in lowercase_last_names:
      #if item == 'Anon'
      if item == name:
        #author_match.append(item) # just say author_match = True?  we don't care how many matches there are, so break?
        author_match = True

    #question -- would it be better to use some sort of similarity score here for last names instead of an exact match?

    # I think exact match is okay since we're only checking last name. Fuzzy match becomes necessary when there are first names OR initials etc etc

def flatten_set_of_tuples(tuples):
    word_list = []
    for tup in tuples:
        word_list.extend(tup)
    return word_list        # yep I think this works

def count_repeats():
  two_or_more = []
  three_or_more = []
  for word in all_words_that_overlap:
    word_counter = 0
    if word in all_words_that_overlap:
      word_counter += 1
      if word_counter >= 3:
        three_or_more.append(word)
      if word_counter >= 2:
        two_or_more.append(word)

def if_any_had_quotes():
  for author in cited_authors:

#input is a list of names, output is just the last name lowercased
def lowercaseLastNames(cited_authors):
    lowercase_last_names=[]
    for name in cited_authors:
        nameParts = name.split()
        #add literal_eval
        lowercase_last_names.append(nameParts[-1].lower())
    return lowercase_last_names

#Test
cited_authors = ["Simon P. Anderson", "Mark Twain", "Ted Overwood", "John Splitsy-Hyphen"] # love splitsy-hyphen!! :)
lowercaseLastNames(cited_authors)         # It's a good idea to run tests like this for each of the functions

#Another way to look at count_repeats:

def count_repeats(all_words_in_overlap):
    words = all_words_in_overlap.split()
    word_counts = Counter(words)
    count_first_condition = any(count >= 3 for count in word_counts.values())
    count_second_condition = sum(count >= 2 for count in word_counts.values()) >= 4
    return count_first_condition and count_second_condition     # nice technique, separating the conditions cdproj
    allows us to change criteria later if we need to

#Two versions of tuple flattening: only need the first one.
#Don't need to worry about word order

def flatten_set_of_tuples(overlapping3grams):
    flattened_set = []
    for tup in overlapping3grams:
        for word in tup:
            if isinstance(word, (str)):
                flattened_set.append(word)
    return(flattened_set)

'''def flatten_set_of_tuples2(overlapping3grams):
    sequence = [i[0] for i in overlapping3grams[:-1]]
    sequence += overlapping3grams[-1]
    return(sequence)'''

# Example usage:
tuples_set3 = {("review", "of", "economic"), ("of", "economic", "studies")}
print(flatten_set_of_tuples(tuples_set3))
#print(flatten_set_of_tuples2(tuples_set3))

#function to find words with quotation marks (single or double) attached to them. We'll need this to compare later with overlapping words from the 3grams.
#It's not perfect because it still picks up apostrophes from conjunctions...

def find_quoted_words(text):
    tokenizedSent = text.split()
    had_quotes = [i for i in tokenizedSent if "\"" in i]
    had_quotes += [i for i in tokenizedSent if "\'" in i]
    had_quotes = [word.strip('\"\'.') for word in had_quotes]
    return had_quotes

# Example
example_text = 'We agree with \'everything\' except Hubble\'s claim that "what we don\'t know cannot kill us."'
find_quoted_words(example_text)

#matching between all the words we found that had overlap and the words that had quotation marks attached to them:
#Question: not every instance of a word had quotation marks attached to it. We need to check whether the correct "instances" of each word are matching..

def did_any_have_quotes(all_words_in_overlap, had_quotes):
    quoted_overlap_words = [i for i in all_words_in_overlap if i in had_quotes]
    return quoted_overlap_words

#Test:
overlapping_words = ['what','is','the','economic','review','doing','about','this']
quoted_words = ['what', 'us', 'everything', "Hubble's", "don't"]
did_any_have_quotes(overlapping_words, quoted_words)

def get_forbidden_combos(cited3grams, citing3grams, had_quotes, cited_authors):
forbidden = []
for idx, citing_set in enumerate(citing3grams):
  if theres_an_author_match(citing_set, lowercase_last_names):   # you can write a function to check this
        forbidden.append(idx)
        continue      # if any author names match any tokens in any of the 3grams, this citing chunk is forbidden
                      # and we can proceed to the next
                      # otherwise, we need to look for quotes
    for cited_set in cited3grams:
            # Then the next thing is, we don't have to compare the 3grams individually.
      # The point of having a set is you can do this ...
      overlapping3grams = cited_set.intersection(citing_set)    # .intersection() finds all the matches
            if len(overlapping3grams) < 4:      # a shared 6-word sequence will create I think four shared 3-grams
          continue                        # if we don't have four, there cannot be a shared 6-word sequence
                                          # so go to the next cited_set
      all_words_in_overlap = flatten_set_of_tuples(overlapping3grams)
                             # I'll imagine you've written a function that turns
                             # a set of tuples into a list of all the words in the tuples
                             # e.g [("review", "of", "economic"), ("of", "economic", "studies")]
                             # ==> ["review", "of", "economic", "of", "economic", "studies"]
            enough_repeats = count_repeats(all_words_in_overlap)
                        # this is a function that checks to see if at least two words appear 3 or more times
                        # and at least four words appear 2 or more times; this must be true if there's a
                        # shared sequence for reasons explained at the end of this document
                        # The function should return True or False
            anything_had_quotes = did_any_have_quotes(all_words_in_overlap, had_quotes)  # left as exercise
            if enough_repeats and anything_had_quotes:
                forbidden.append(idx)
                break      # we don't need to compare it to any other chunks of the cited document
                           # because one match is enough to condemn it

# def get_forbidden_combos(cited3grams, citing3grams, had_quotes, cited_authors):
#   #INPUTS
#   cited_file = #list of chunks (each chunk is a set of 3 grams) from cited file
#   citing_file = #list of 3 gram chunks from citing file
#   words_set_list = #citing file chunk represented as a set of indivual words (quoted, but no longer has quotes attached)
#   cited_authors = #authors cited by the citing file?
#   #Function's Mission
#   #return a list of indexes from the citing file, of chunks that contained either a last name or at least 6 words in sequence shared with any chunk (and one of those words had quotes attached)
#   index_list = []
#   for items in cited_file:
#     for grams in citing_file:
#       if item == gram:
#         for index in cited_file:
#           index_list.append(index) #should identify any matches between the 3 gram sets? -- but I think it is supposed to be 6 words instead...
#       for name in cited_authors:
#         if name == item:
#           index_list.append(index)
#   return(index_list)

#read in the chunks: from the campus cluster, text files (don't actually have to do this? write function assumed passed 2 articles you want to compare, he will write framework to handle metadata)
#spreadsheet with semantic scholar





# convert each chunk into dictionary (or set) of three grams, using NLTK
#moving window of 3 words, set of 3 grams
#one article in the future and all its chunks are sets of three grams
#compare using setname.intersection other setname
#need to have at least 4 in common
#most chunks will fail that


#set of 3 grams in the entire article, not just the chunk, if not at least 5 of the 3 grams in common with whole article
#then for those in common, do the indivual chunk comparisons
#look at the set of 3 grams shared b/w the chunks, something needs to be true about the words that compose those, if they overlapped/part of the same string
#how many words are shared between those 3 grams
#4 words that occur 3 times within the set
#count #from collections import counter, like a dictionary but starts everything at 0, increment the count

#put all strings together, make counter list of words
#find 3 words that are repeated 3 times

#delta folder with the chunks


#identify the DOI, each is a seperate line of the file, no extraneous new lines
#each line is a chunk, split on the tab and take everything after the chunk

#bbiq
#embedding code folder
#results of the scripts
#subfolder called chunks
#last part of DOI
#list of chunks
#chunk #, tab, up to 512 tokens

#start with json to see cited
#spreadsheet with titles and author and year, (metadata, 20 years in future etc and also listed as citing this
#then citations json file in email and find the subset
#then read in the chunks, each article is a seperate, named with semantic scholar ID
#semantic scholar ID.txt files

#for one cited article and its metadata and the list of file IDs for articles that cite that article
#read in/define article as its chunks?
article_metadata = []
#this is in the github repo, when we search semantic scholar for list of citations, we output spreadsheet with author, title etc, BUT also need JSON lines file where each article represented for a specific JSON with the specific articles that cite it
#prob represented by a semantic scholar ID, but have to
#JSONS from semantic scholar
article_cited = []
#for each chunk, if more than 4 of those three word phrases are shared between 2 articles = overlap phrase
#if more than 3 and shared phrases share words then = overlap phrase
#when there's an overlap phrase, we will exclude that chunk from our final output (probably not at this point though)
#store the ID correlated with the chunk that has a overlap phrase
#cited article and list of IDs that cite it
#create a dictionary of how many chunks are in each file (aka list of chunk IDs in each article)
#function returns the "forbidden" chunks we need to exclude/that cannot be compared to our article


#lopp thru
#if author name in chunk, add this chunk ID to list of forbidden